name: Register New Author

on:
    workflow_dispatch:
      inputs:
        author:
          type: string
          description: 'Full name'
          required: true
        affiliation1:
          type: string
          description: 'First affiliation'
          required: true
        affiliation2:
          type: string
          description: 'Second affiliation'
          required: false
        affiliation3:
          type: string
          description: 'Third affiliation'
          required: false
        orcid:
          type: string
          description: 'ORCID'
          required: false
        email:
          type: string
          description: 'Email address (will be public!!)'
          required: false


jobs:
    update:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
                cache: 'pip' # caching pip dependencies
      
            - name: Install requirements
              run: |
                pip install -U pip
                pip install pyaml pyperclip
            
            - name: Install authors package
              run: |
                pip install -e .
            
            # - name: Upload Known Authors
            #   uses: EndBug/add-and-commit@v9
            #   with:
            #     add: '[ "authors/data/all_known_authors.yml" ]'
            #     pull: '--rebase --autostash'

            # - name: Test
            #   run: |
            #     cat authors/data/all_known_authors.yml
