name: Update Author Name

on:
    workflow_dispatch:
      inputs:
        old_name:
          type: string
          description: 'Old name of the author'
          required: true
        new_name:
          type: string
          description: 'New name of the author'
          required: true

jobs:
    update:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
                cache: 'pip' # caching pip dependencies
      
            - name: Install requirements
              run: |
                pip install -U pip
                pip install pyaml pyperclip
            
            - name: Install authors package
              run: |
                pip install -e .
            
            - name: Update
              run: |
                update-author-name "${{ github.event.inputs.old_name }}" "${{ github.event.inputs.new_name }}"

            - name: Upload Known Authors
              uses: EndBug/add-and-commit@v9
              with:
                add: '[ "authors/data/all_known_authors.yml" ]'
                pull: '--rebase --autostash'

            # - name: Test
            #   run: |
            #     cat authors/data/all_known_authors.yml
