name: Update Author Email

on:
    workflow_dispatch:
      inputs:
        author:
          type: string
          description: 'Full name of the author'
          required: true
        email:
          type: string
          description: 'Email address of the author'
          required: true

jobs:
    update:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
                cache: 'pip' # caching pip dependencies
      
            - name: Install requirements
              run: |
                pip install -U pip
                pip install pyaml pyperclip
            
            - name: Install authors package
              run: |
                pip install -e .
            
            # - name: Update
            #   run: |
            #     update-author-email ${{ github.event.inputs.author }} ${{ github.event.inputs.email }}
